dist: xenial

language: python

services:
  - docker

python:
  - "3.5"

install:
  - make deps
  - sudo apt-get –-no-install-recommends -y install sshpass

script:
  - make check check-sr NGSDN_TUTORIAL_SUDO=sudo
